package de.symeda.sormas.api.person;

import de.symeda.sormas.api.i18n.I18nProperties;

public enum Nationality {

	NONE,
	AFGHAN,
    ALBANIAN,
    ALGERIAN,
    ANDORRAN,
    ANGOLAN,
    ANTIGUAN_AND_BARBUDAN,
	ARGENTINE,
    ARMENIAN,
    AUSTRALIAN,
    AUSTRIAN,
    AZERBAIJANI,
	BAHAMIAN, BAHRAINI, BANGLADESHI, BARBADIAN, BELARUSIAN, BELGIAN, BELIZEAN, BENINESE, BUTHANESE, BOLIVIAN,
	BOSNIAN_AND_HERZEGOVINIAN, BOTSWANAN, BRAZILIAN, BRUNEIAN, BULGARIAN, BURKINABE, BURUNDIAN, CAMBODIAN, CAMEROONIAN,
	CANADIAN, CAPE_VERDIAN, CENTRAL_AFRICAN, CHADIAN, CHILEAN, CHINESE, COLOMBIAN, COMORAN, CONGOLESE_CD, CONGOLESE_CG,
	COSTA_RICAN, CROATIAN, CUBAN, CYPRIOT, CZECH, DANISH, DJIBOUTI, DOMINICAN_DM, DOMINICAN_DO, EAST_TIMORESE,
	ECUADOREAN, EGYPTIAN, EQUATORIAL_GUINEAN, ERITREAN, ESTONIAN, ETHIOPIAN, IVORIAN, SALVADORAN,
    OTHER
	;
	
	public String toString() {
		return I18nProperties.getEnumCaption(this);
	};
}
